### ISSUE TITLE
输出坐标

### ISSUE THREAD

**Issue by SSTato** [bubbliiiing/deeplabv3-plus-pytorch#32]
![image](https://user-images.githubusercontent.com/93987794/183868761-16e250ee-ea6c-4f38-a21c-fb3969eef72d.png)
        if self.mix_type == 0:
            seg_img = np.zeros((np.shape(pr)[0], np.shape(pr)[1], 3))
            for c in range(self.num_classes):
                seg_img[:, :, 0] += ((pr[:, :] == c ) * self.colors[c][0]).astype('uint8')
                seg_img[:, :, 1] += ((pr[:, :] == c ) * self.colors[c][1]).astype('uint8')
                seg_img[:, :, 2] += ((pr[:, :] == c ) * self.colors[c][2]).astype('uint8')

请问如果我想得到这个猫的左上方坐标和右下方坐标该怎么print呢

**Comment by bubbliiiing** [comment]
所有点坐标的min和max

**Comment by SSTato** [comment]
> 所有点坐标的min和max

可以提供一下输出代码吗，没找到坐标信息在哪里。

**Comment by bubbliiiing** [comment]
你可以用np.where先求坐标
