### ISSUE TITLE
训练时会卡住不动

### ISSUE THREAD

**Issue by superxianyuwang** [bubbliiiing/deeplabv3-plus-pytorch#7]
请问我使用自己的数据进行训练时，会出现跑到中途就卡住，然后就自动结束进程，请问知道是什么原因吗？
![dba8f686189f555b38af8dade1ee802](https://user-images.githubusercontent.com/90171870/145523371-312a74b3-6ee6-4168-8efd-656053e71ee1.png)

**Comment by superxianyuwang** [comment]
感谢您的讲解和代码

**Comment by bubbliiiing** [comment]
是不是被其它程序中断了，你看看内存什么的，正常吗
