### ISSUE TITLE
TF/Keras 版和 PyTorch 版的性能差异

### ISSUE THREAD

**Issue by fyang93** [bubbliiiing/deeplabv3-plus-pytorch#8]
首先感谢提供多种版本的代码。
我注意到同样是`VOC12`数据集，`deeplabv3-plus-tf2`/`deeplabv3-plus-keras`在测试集上的结果显著优于`deeplabv3-plus-pytorch`版本。
是否因为前者使用的是`dice_loss_with_CE`而后者只使用`DiceLoss`进行训练？还是有其它别的原因？

**Comment by bubbliiiing** [comment]
0 0没，因为前者预训练权重更好

**Comment by fyang93** [comment]
仔细看了下这边的loss也是CE和diceloss加在一起了。原来是预训练模型不一样，emm，也许可以用onnx统一一下

**Comment by bubbliiiing** [comment]
0 0
